/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-08-09 11:12:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.egovframework.example.sendmail;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/jsp/egovframework/example/sendmail/../sendmail/layout/header.jsp", Long.valueOf(1628505721884L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-jstl-1.2.jar", Long.valueOf(1627914579451L));
    _jspx_dependants.put("jar:file:/C:/Workspace/eGov/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sendmail/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/egovframework.rte.ptl.mvc-3.9.0.jar", Long.valueOf(1627914580045L));
    _jspx_dependants.put("jar:file:/C:/Workspace/eGov/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sendmail/WEB-INF/lib/egovframework.rte.ptl.mvc-3.9.0.jar!/META-INF/taglib.tld", Long.valueOf(1578030854000L));
    _jspx_dependants.put("jar:file:/C:/Workspace/eGov/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sendmail/WEB-INF/lib/spring-webmvc-4.3.22.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1546991294000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.22.RELEASE.jar", Long.valueOf(1627914562140L));
    _jspx_dependants.put("jar:file:/C:/Workspace/eGov/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sendmail/WEB-INF/lib/spring-webmvc-4.3.22.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1546991294000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- 윗 부분 넣어줘야 한글 안깨짐 --> \r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("\ttext/html을 지우면 생기는 애러 : 다른 값들을 가지는 'contentType'이 여러 번 나타나는 것은 불허됩니다. (이전 값: [text/html; charset=utf-8], 신규 값: [charset=utf-8])]을(를) 발생시켰습니다\r\n");
      out.write("\t (+ \"text/html;charset=utf-8\" 요렇게 붙여쓰면 애러가 -> 신규 값: [text/html;charset=utf-8]~ 로 난다.)\r\n");
      out.write("\t (+ charset=utf-8을 지우면 애러가 -> 신규 값: [text/html]~~ 로 난다.)\r\n");
      out.write("\t그냥 아얘 아래 JSP태그를 지우면 '로그아웃 하시겠습니까?'라는 알림창 한글이 깨진다. 즉, 아래 태그는 jsp에서 이벤트창으로 아래 logout()과 같은 함수 호출시 UTF-8을 적용시키는 것 같다.\r\n");
      out.write("\tpageEncoding=\"utf-8\" 지워도 우선 애러는 안나서 일단 지움. \r\n");
      out.write("\t--> \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("<!-- jstl을 쓰기위해서 넣어준다. 아래 설정 주석시 뭔가 웹페이지 모양이 이상해진다. 적용이 된다는 것. \r\n");
      out.write("          하지만  taglib의 경우 웹페이지 f12의 Elements에서 보이진 않는다.  -->\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\"> \r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <meta name=\"description\" content=\"\">\r\n");
      out.write("  <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom fonts for this template--> \r\n");
      out.write("  <!-- href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" 이렇게도 된다. 기본이 webapp에서 출발 -->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("  <link\r\n");
      out.write("      href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("      rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Custom styles for this template-->\r\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>  \r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" defer=\"defer\" >\r\n");
      out.write("\t \r\n");
      out.write("\tfunction logout() {\r\n");
      out.write("\t\tif( !confirm(\"로그아웃 하시겠습니까?\") ){\r\n");
      out.write("\t\t\treturn;\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tlocation.href = \"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 전체 체크 구현\r\n");
      out.write("\tfunction selectAll(This)  {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t// 상단 체크박스 체크되어 있을때만 삭제버튼 활성화 시킴\r\n");
      out.write("\t\t\tif (This.checked) {\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#delBtn, #delBtn2\").attr(\"disabled\", false);  // 활성화\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\"#delBtn, #delBtn2\").attr(\"disabled\", true);   // 비활성화\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// document.getElementById('delBtn').setAttribute(\"disabled\", false);\t자바스크립트로는 왜 안되지??\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 상단 체크박스에 따라서 아래 체크박스들 전체 컨트롤 됨\r\n");
      out.write("\t\t  const checkboxes = document.getElementsByName('select_each');\t// 메일 체크박스들\r\n");
      out.write("\t\t  checkboxes.forEach((checkbox) => { \r\n");
      out.write("\t\t\t    checkbox.checked = This.checked;\r\n");
      out.write("\t\t  }); \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 모든 메일 체크박스 체크시 상단체크박스 체크되게함\r\n");
      out.write("\tfunction selectEach()  {\r\n");
      out.write("\t\t  const checkAll = document.getElementById('select_all');\t// 전체 체크해주는 상단체크박스\r\n");
      out.write("\t\t  const checkboxes = document.getElementsByName('select_each');\t// 메일 체크박스들\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  let cntChecked = 0;\t\t\t\t\t\t\t\t\t// 체크된 메일수\r\n");
      out.write("\t\t  checkboxes.forEach((checkbox) => {\r\n");
      out.write("\t\t\t    if(checkbox.checked) {\r\n");
      out.write("\t\t\t    \tcntChecked = cntChecked + 1;\r\n");
      out.write("\t\t\t    };\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  // 모든 메일의 체크박스 갯수가 체크된 체크박스의 수가 같으면, 즉 모든 체크박스 선택시 상단 체크박스 체크됨.\r\n");
      out.write("\t\t  if (cntChecked == checkboxes.length) {\r\n");
      out.write("\t\t\t\tcheckAll.checked = true;\r\n");
      out.write("\t\t  } else {\r\n");
      out.write("\t\t\t  checkAll.checked = false;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t  // 하나 이상의 메일의 체크박스가 체크되어 있다면 삭제버튼 활성화 시킴 \r\n");
      out.write("\t\t  if (cntChecked >= 1) {\r\n");
      out.write("\t\t\t  $(\"#delBtn, #delBtn2\").attr(\"disabled\", false); \r\n");
      out.write("\t\t  } else {\r\n");
      out.write("\t\t\t  $(\"#delBtn, #delBtn2\").attr(\"disabled\", true); \r\n");
      out.write("\t\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 선택한 메일들 임시삭제 구현(VO의 checkedIdxs로 들어감)\r\n");
      out.write("\tfunction deleteTmp() {\r\n");
      out.write("\t\t\t// confirm(\"a\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t    var checkedIdxs = [];    \t\t\t\t\t\t\t // 배열 초기화\r\n");
      out.write("\t    $(\"input[name='select_each']:checked\").each(function() {\r\n");
      out.write("\t    \tcheckedIdxs.push($(this).val());     // 체크된 것만 값을 뽑아서 배열에 push\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    document.location.href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" + checkedIdxs;\t\t// document빼도 잘 작동함\r\n");
      out.write("\t \t\t// http://localhost/sendmail/deleteTmp.do?checkedIdxs=20,21\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t    // 배열로 전달함\r\n");
      out.write("\t/*     $.ajax({\r\n");
      out.write("\t        url: 'deleteTmp2.do'\r\n");
      out.write("\t        , type: 'post'\r\n");
      out.write("\t        , dataType: 'text'\t\t\t\t// dataType과 data는 넘겨주는 값이 있는 경우에만 작성하면 됨.\r\n");
      out.write("\t        , data: {\r\n");
      out.write("\t        \tvalueArr: checkArr\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }); \r\n");
      out.write("\t*/\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 휴지통에서 완전삭제\r\n");
      out.write("\tfunction deleteMail() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t    var checkedIdxs = [];    \t\t\t\t\t\t\t \r\n");
      out.write("\t    $(\"input[name='select_each']:checked\").each(function() {\r\n");
      out.write("\t    \tcheckedIdxs.push($(this).val());     \r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    document.location.href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" + checkedIdxs;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 휴지통에서 메일함으로 복원\r\n");
      out.write("\tfunction restoreMail() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t    var checkedIdxs = [];    \t\t\t\t\t\t\t \r\n");
      out.write("\t    $(\"input[name='select_each']:checked\").each(function() {\r\n");
      out.write("\t    \tcheckedIdxs.push($(this).val());     \r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    document.location.href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" + checkedIdxs;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$( document ).ready(function() {\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function check() {\r\n");
      out.write("\t// alert('1');\r\n");
      out.write("\tif( $('#user_id').val() == '') {\r\n");
      out.write("\t\talert(\"아이디를 입력하세요!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif( $('#password').val() == '') {\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-gradient-primary\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Outer Row -->\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-xl-10 col-lg-12 col-md-9\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card o-hidden border-0 shadow-lg my-5\">\r\n");
      out.write("                    <div class=\"card-body p-0\">\r\n");
      out.write("                        <!-- Nested Row within Card Body -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-6 d-none d-lg-block bg-login3-image\"></div>\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <div class=\"p-5\">\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <form class=\"user\" method=\"post\" action=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("                                        <div class=\"form-group\">\t\t\t\t\t\t\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control form-control-user\"\r\n");
      out.write("                                                id=\"user_id\" name=\"user_id\" \r\n");
      out.write("                                                placeholder=\"ID\"> \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"password\" class=\"form-control form-control-user\"\r\n");
      out.write("                                                id=\"password\" name=\"password\" placeholder=\"Password\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <button type=\"submit\" onclick=\"return check();\" class=\"btn btn-primary btn-user btn-block\">\r\n");
      out.write("                                            Login\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath());
      out.write("/css/bootstrap/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/egovframework/example/sendmail/../sendmail/layout/header.jsp(30,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/bootstrap/vendor/fontawesome-free/css/all.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/egovframework/example/sendmail/../sendmail/layout/header.jsp(38,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/js/jquery-3.5.1.min.js");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/jsp/egovframework/example/sendmail/../sendmail/layout/header.jsp(46,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/logout.do");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/jsp/egovframework/example/sendmail/../sendmail/layout/header.jsp(103,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/deleteTmp.do?checkedIdxs=");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/jsp/egovframework/example/sendmail/../sendmail/layout/header.jsp(127,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/delete.do?checkedIdxs=");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/jsp/egovframework/example/sendmail/../sendmail/layout/header.jsp(138,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/restore.do?checkedIdxs=");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/egovframework/example/sendmail/login.jsp(8,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty msg}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("    \talert(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"); \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/jsp/egovframework/example/sendmail/login.jsp(47,77) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/login.do");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }
}
